### ISSUE TITLE
New main fork

### ISSUE THREAD

**Issue by codexGW** [A3Armory/A3A_A3Wasteland.Altis#1]
This is the new main fork we can use for unique addons  and changes to A3Wasteland.

**Comment by gravcat** [comment]
Just to make sure you were aware, you had branched (not forked). Branching is appropriate in this situation, but just in case you really meant to fork just a heads-up. :smile:

**Comment by codexGW** [comment]
It was done on purpose. You're very limited when you or on a fork. You
can't even use the search feature on the website.

**Comment by gravcat** [comment]
Of course, just making sure you had meant to since the issue reads "New main fork" - carry on!
