### ISSUE TITLE
Laser Designator Thermal Imaging

### ISSUE THREAD

**Issue by x-bacon** [A3Armory/A3A_A3Wasteland.Altis#11]
Since the new update I've noticed that Laser Designators do not have thermal anymore. I wish to enable that again, but i've tried in so many different ways that I am starting to believe it is impossible. Don't know if it is only me, or if you've done it on purpose. Please help me out! :) I have tried messing arround with every single line of code that could have anything to do with thermals without success.. Please do not tell me to set "A3W_disableBuiltInThermal" to 0 because that was the first thing i tried without success.

**Comment by codexGW** [comment]
Here you go.
https://github.com/A3Armory/A3A_A3Wasteland.Altis/commit/7a48b5f1d60a650feb6a1f2e55707e7d420f4083

The main repo is here.
https://github.com/A3Wasteland/ArmA3_Wasteland.Altis

**Comment by x-bacon** [comment]
Funny thing, my that exact line of code was already updated for me, but thermals on the laser designator are still down. It's weird that there's no black screen no "thermals offline" message displayed, it is just like the vehicles where it switches from night vision to normal view. This is getting me frustrated, don't know what to do anymore.

**Comment by x-bacon** [comment]
Also I forgot to mention, when running the server on my machine, if I am the host the laser designator works just fine for me, but all other players who connect to my server aren't able to use it. Don't know what could be causing such issue, I'm almos killing myself after 5 days of looking at the code without a single inch of success. D:

**Comment by x-bacon** [comment]
One last detail: First time I ran a my server to try the laser designator, a error message saying something like: "bad vehicle type" was displayed. it only happened once though, hasn't happened again since then. I believe this glitch is coming from the code that blocks vehicle thermals.

**Comment by codexGW** [comment]
We are not experiencing this issue on any of the servers. I'll let you know if I see or hear any thing.
