### ISSUE TITLE
Admin log not working on low and high admins

### ISSUE THREAD

**Issue by codexGW** [A3Armory/A3A_A3Wasteland.Altis#13]
For some reason the admin panel is only logging serverOwners use of the admin panel. Not sure what broke it but it was probably this commit https://github.com/A3Armory/A3A_A3Wasteland.Altis/commit/7a72d1f4e6326263490543009958e63b7203bc6f

When I commented out this [line](https://github.com/A3Armory/A3A_A3Wasteland.Altis/blob/dev/server/antihack/notifyAdminMenu.sqf#L11), logging worked. Any thoughts on if this was the right fix or will it screw up anything else? It looks like isAdmin function is broken for lowAdmins and highAdmins but I'm at a loss.

**Comment by codexGW** [comment]
Fixed it. Still don't get the need for the 3 in this [line](https://github.com/A3Armory/A3A_A3Wasteland.Altis/commit/73f251d1a1bc41a3f79716f07b1cbc15c02ae756#diff-1c3d38cc2a26bd4d6432a11e808cfb77L11) but oh well.
https://github.com/A3Armory/A3A_A3Wasteland.Altis/commit/73f251d1a1bc41a3f79716f07b1cbc15c02ae756

**Comment by pAxton-** [comment]
You are defaulting it's case selection in this switch statement in the isAdmin.sqf

**Comment by AgentRev** [comment]
the 3 was not needed. ~~your fix is invalid and will cause the function to fail.~~

**Comment by codexGW** [comment]
Thanks for the info guys. I don't believe I had logging off for low and high admins for 3 months. I thought they just weren't using it too much... lol
