### ISSUE TITLE
Add a check for any current water missions

### ISSUE THREAD

**Issue by codexGW** [A3Armory/A3A_A3Wasteland.Altis#14]
I'm trying to add a check for any current water missions before any new ones pop up. I've been getting complaints about 2 sometimes 3 water missions going. Where would I add a check? Any help with the logic would be helpful too.

**Comment by tylers-dev** [comment]
https://github.com/A3Armory/A3A_A3Wasteland.Altis/commit/f1fc0fc03a037c6ecc764cd20eac4a1407754bc1

**Comment by codexGW** [comment]
Noice
