### ISSUE TITLE
mARMA death logging help

### ISSUE THREAD

**Issue by codexGW** [A3Armory/A3A_A3Wasteland.Altis#21]
I'm trying to get all deaths logged so I can tell who is teamkilling who. Any ideas where I should do this?

Here's my shitty attempt.
https://github.com/A3Armory/A3A_A3Wasteland.Altis/commit/72bf6953e9561e06563653008b09efbf942a07b1

**Comment by Gigatek1** [comment]
I'll give it a go. I don't know if this will work client side.
