### ISSUE TITLE
Money Mission

### ISSUE THREAD

**Issue by bondrj** [A3Armory/A3A_A3Wasteland.Altis#23]
I honestly do not know how I can explain this.
All the missions works perfectly, however the missions: Small Money Shipment, Medium Money Shipment, Large Money Shipment, Heavy Money Shipment. It does not attack the player if it is tank or any AA vehicle.

If he gets off the vehicle the mission attacks normal. So far I can not say where the error came from. Well, I'm working with the bots in HARDCORE mode.

**Comment by codexGW** [comment]
I'll test this out when I get a chance. I'll make sure to test vanilla A3Wasteland as well just in case.

**Comment by codexGW** [comment]
Just did some testing and it seems all AI don't engage if you are in a vehicle until you shoot at them. @AgentRev The defendArea.sqf script could be improved maybe. Or maybe add a check for them to be setCombatMode "RED" if any players are near by.

**Comment by codexGW** [comment]
https://community.bistudio.com/wiki/Side_relations

This might help AI to attack all vehicles

**Comment by AgentRev** [comment]
😒 https://github.com/A3Wasteland/ArmA3_Wasteland.Altis/blob/dev/server/functions/relations.sqf

**Comment by codexGW** [comment]
Lol I see. Yeah good ol' Arma.

**Comment by codexGW** [comment]
Maybe it needs to be set to the vehicle too ¯\_(ツ)_/¯. I'll look at it more this weekend maybe.
