### ISSUE TITLE
Explosives in Gun Store

### ISSUE THREAD

**Issue by Merciful78** [A3Armory/A3A_A3Wasteland.Altis#24]
It is possible to plant explosives in the Gun Store Area. Satchels, charges, and mines are able to be activated by dropping them on the ground through the inventory. You can then look at them and a "Check mark" will appear on the center of your screen. Press your "select action" key and the explosive is now activated. An explosive charge can now be detonated remotely or use the timer. APRS mines also seem to work as intended using the same work-around.

**Comment by codexGW** [comment]
Just in case you didn't get a notification. @AgentRev I'll try to think of a solution this weekend if you don't by then.

**Comment by gravcat** [comment]
I'm not versed in scripting with ARMA specifically, but is there not an event or emitter that can be subscribed to for explosives placements? Would it not be possible to just trigger a delete of that element of entity upon placement thereafter? Even if it were possible I'm not sure if there's any issues with that leaving 'garbage' behind anywhere else though.

Just kinda spitballing. I'm curious to get involved but I don't know where to start!

**Comment by codexGW** [comment]
I would try the delete when placed around a npc if I cant find a way to block dropping certain items from the inventory (might be some weird BI function or command that does it). If not I would start with the way its done already with the action to start with. I usually just get examples from BI or Frankenstein something Agent or others have already done.

https://community.bistudio.com/wiki/Category:Scripting_Commands_Arma_3
https://github.com/A3Armory/A3A_A3Wasteland.Altis/blob/dev/client/functions/fn_inGameUIActionEvent.sqf#L12-L115

**Comment by codexGW** [comment]
This might help too
http://foxhound.international/ARMA-3-SQF-Cheat-Sheet-Revision-3.pdf
This is great if you use notepad ++
http://www.armaholic.com/page.php?id=8692

**Comment by codexGW** [comment]
Does any one know the action for "Activate mine"? I can only find deactivateMine
https://community.bistudio.com/wiki/Arma_3_Actions

```
		case (_action == "deactivateMine"):
		{
			_minDist = ["A3W_remoteBombStoreRadius", 100] call getPublicVar;
			if (_minDist <= 0) exitWith {};

			_nearbyStores = entities "CAManBase" select {_x getVariable ["storeNPC_setupComplete", false] && {player distance _x < _minDist}};

			if !(_nearbyStores isEqualTo []) exitWith
			{
				playSound "FD_CP_Not_Clear_F";
				[format ["You are not allowed to activate place explosives within %1m of a store.", _minDist], 5] call mf_notify_client;
				_handled = true;
			};
		};
```
This worked but when I tried activateMine it did not work. WTH would they have deactivateMine but not activateMine?

**Comment by AgentRev** [comment]
What do you mean by "activating" a mine? Place it? Detonate?

**Comment by codexGW** [comment]
You can bypass the store bomb action block if you drop the bomb or mine from your inventory on the ground. The action "Activate mine" is available and works.

**Comment by AgentRev** [comment]
Well that's new... Put a `systemChat _action` in fn_inGameUIActionEvent.sqf to find out the name!

**Comment by codexGW** [comment]
Oh yeah, smart... I will mess with it later tonight. Thank you

**Comment by codexGW** [comment]
It was UseContainerMagazine. ActivateMine is there in the cfg but maybe BI is saving it for later.
`[bin\config.bin/CfgActions/UseContainerMagazine,bin\config.bin/CfgActions/ActivateMine]` 

Here's the action added
https://github.com/A3Armory/A3A_A3Wasteland.Altis/commit/a5efbd904da4507db7084129e7007007ab23e1d6

**Comment by codexGW** [comment]
Forgot the other locations. 
https://github.com/A3Armory/A3A_A3Wasteland.Altis/commit/e1882c8f53e7021e9b5756ebe2d018ff55ed097d
