### ISSUE TITLE
Helicopter Airlift Script Not Required

### ISSUE THREAD

**Issue by SpanishSurfer** [A3Armory/A3A_A3Wasteland.Altis#26]
Good day fellas! I'm a casual Wasteland player and noticed you guys are still using the airlift scripts from the pre "Helicopter DLC" BIS released a while back. I just wanted to inform you that these old lift scripts are not required anymore, the slingload function is built in game and always on (like the bipod script).

**Comment by codexGW** [comment]
You can still use the BIS method if you want, right? Haven't flown on a sling load capable helicopter for awhile.

**Comment by SpanishSurfer** [comment]
Yes it's enabled buy default making the script obsolete.

**Comment by codexGW** [comment]
Oh okay. That would be simple one to do. Just remove the R3F lift script actions for the right vehicles. I would start a topic with a vote to see if that's what people want on our forum. I don't know if people want to be dealing with it or not really. I don't fly enough to make a fair opinion.

**Comment by AgentRev** [comment]
> not required anymore

This subject was already discussed numerous times in the past. The R3F system is much more sturdy and versatile. The vanilla slingload is a pathetic non-customizable gimmick. I don't understand why you would even request this.

**Comment by SpanishSurfer** [comment]
Ok, well thats your decision. However the descriptions you gave regarding slingloading are totally inaccurate.

**Comment by AgentRev** [comment]
Ok, here's a better one:

> gar·bage
> /ˈɡärbij/
> _noun_ North American
> 
>   wasted or spoiled food and other refuse, as from a kitchen or household.
>  _synonyms_: trash, rubbish, refuse, waste, detritus, litter, junk, scrap
>    - a thing that is considered worthless or meaningless.
>         "a store full of overpriced garbage"
