### ISSUE TITLE
Enhanced Movement Script

### ISSUE THREAD

**Issue by SpanishSurfer** [A3Armory/A3A_A3Wasteland.Altis#27]
Ability to climb over objects, climb onto roof tops, etc. Animations look pretty great, the script can be inserted for client side use, no unnecessary loops, and it goes off the weight you carry. So a fully loaded soldier can't climb over a wall.  This script is on our BECTI server and we have not had any issues with it.

Wasteland could def use this!

https://steamcommunity.com/sharedfiles/filedetails/?id=333310405

**Comment by codexGW** [comment]
If its anything like [Advanced Rappelling](https://github.com/A3Armory/A3A_A3Wasteland.Altis/commit/17e8965bbe6396dc51907542feac85e705df2017) I was told it would lag the server bad. Definitely would like some feedback from others who run a a3w server and AgentRev as well. It looks cool.

Here's the official issue tracker and forum for A3Wasteland
https://github.com/A3Wasteland/ArmA3_Wasteland.Altis/issues
http://forums.a3wasteland.com/

**Comment by SpanishSurfer** [comment]
Rappeling lags because of the client to client relationship involved. This script doesnt depend on another player hence no lag.

**Comment by codexGW** [comment]
Is this a client mod? They kill the servers pop.

**Comment by SpanishSurfer** [comment]
No, built into the mission. No download required

**Comment by codexGW** [comment]
Cool, if you want do a pull request and we can add it. We can always revert if it causes a lot of issues.

**Comment by SpanishSurfer** [comment]
Sure if the feedback leans that way I'll do it

**Comment by codexGW** [comment]
Let me know if you need help with anything.
