### ISSUE TITLE
Bounty

### ISSUE THREAD

**Issue by ghost** [A3Armory/A3A_A3Wasteland.Altis#28]
Hey,

By now i assume Rev doesn't want or has time to implement the Bounty feature into vanilla wasteland so would you mind if i used this, but also could someone explain how this should be implemented please

thanks

**Comment by codexGW** [comment]
Agent put the framework in and I believe he's had enough request for it too to implement. He probably hasn't had the time to do it. I believe he said something about this summer, but that was awhile ago. It might be best to wait until we hear from him to prevent conflicts. 

There was some fixes and tweaks but if you go through the history thoroughly you can find all the commits.
https://github.com/A3Armory/A3A_A3Wasteland.Altis/commits/dev/addons/bounty

**Comment by codexGW** [comment]
https://github.com/A3Armory/A3A_A3Wasteland.Altis/search?utf8=%E2%9C%93&q=bounty&type=
