### ISSUE TITLE
Vehicle store issues

### ISSUE THREAD

**Issue by codexGW** [A3Armory/A3A_A3Wasteland.Altis#31]
I'm having issues with the vehicle store timeout not working but the bad one is the vehicle store isn't taking money when I buy a vehicles sometime. Not sure what cause it but once its active everything you buy at the vehicle store is free.

**Comment by codexGW** [comment]
Oh nooo. It's happening on vanilla. @AgentRev need a quick fix. DLC is coming in 1 hour.

**Comment by AgentRev** [comment]
client rpt plz

**Comment by AgentRev** [comment]
actually, server rpt plz

**Comment by Gigatek1** [comment]
[Arma3_x64_2017-05-16_04-28-45.zip](https://github.com/A3Armory/A3A_A3Wasteland.Altis/files/1004262/Arma3_x64_2017-05-16_04-28-45.zip)

**Comment by Gigatek1** [comment]
Server coming
[arma3server_x64_2017-05-16_04-51-38.zip](https://github.com/A3Armory/A3A_A3Wasteland.Altis/files/1004265/arma3server_x64_2017-05-16_04-51-38.zip)

**Comment by codexGW** [comment]
Don't worry about this. Testing something

4:53:09 Error in expression <ings\main_config.sqf"

_rNumber = floor random [4,22];
A3W_startHour = _rNumber;>
 4:53:09   Error position: <random [4,22];
A3W_startHour = _rNumber;>
 4:53:09   Error 2 elements provided, 3 expected
 4:53:09 File A3Wasteland_settings\main_config.sqf, line 2

**Comment by AgentRev** [comment]
you shouldn't use an array like that with `random`, it's not a linear range, but a gaussian distribution. use this:

    #define RANDOM_BETWEEN(START,END) ((START) + floor random ((END) - (START) + 1))

**Comment by AgentRev** [comment]
ok I have the bug too, looking into it

**Comment by AgentRev** [comment]
oh lol just a small bug with `params`, hang on.

**Comment by AgentRev** [comment]
https://github.com/A3Wasteland/ArmA3_Wasteland.Altis/commit/26b97344052c161c230c232408107a1fa3c1e336
