### ISSUE TITLE
Resupply price

### ISSUE THREAD

**Issue by codexGW** [A3Armory/A3A_A3Wasteland.Altis#32]
Any idea what broke this? I'm at a loss

https://github.com/A3Armory/A3A_A3Wasteland.Altis/blob/dev/client/functions/fn_resupplyTruck.sqf#L53-L60

**Comment by AgentRev** [comment]
It never worked in the first place, you are comparing an object to an array of strings. Instead,

    if ({_vehicle isKindOf _x} count _isHighPrice > 0) then

**Comment by codexGW** [comment]
Yeah that's was thinking after I sent the issue (I needed to use count) but I swear it worked when I tested it. Maybe I was really stoned. 😃 Thanks Agent
