### ISSUE TITLE
Ejection seat and windshield?

### ISSUE THREAD

**Issue by codexGW** [A3Armory/A3A_A3Wasteland.Altis#33]
I would like to find the model/class names for the ejection seat and windshield. The seat is a vehicle lol; you can get in and it even has a option to unflip it. I would like to add them to our clean-up script.

**Comment by AgentRev** [comment]
They are added directly to the vehicle wreck garbage collector, they are removed every 10 min.

**Comment by codexGW** [comment]
Nice
