### ISSUE TITLE
Karts and similar vehicles locked from store...

### ISSUE THREAD

**Issue by usszulu2** [A3Armory/A3A_A3Wasteland.Altis#38]
Karts, Hatchbacks, and other vehicles that are not normally lockable will spawn from vehicle stores locked. There is no way to unlock these vehicles, so they are inaccessible. I tested this using vehicles on Stratis.

**Comment by usszulu2** [comment]
So far affected vehicles are the ATV, Kart, Offroad, SUV, MB-4WD, and probably all the boats as I assume none of those are supposed to lock.  Also be advised this was on Giga's test server.

**Comment by codexGW** [comment]
Found it. It was this setting. I wonder how long it was like this 🙄 . It's kind of silly to exclude unlock as well. I'll just remove it.
https://github.com/A3Armory/A3A_A3Wasteland.Altis/blob/dev/addons/vactions/config.sqf#L29

**Comment by AgentRev** [comment]
The config comment is incorrect, you can't leave the first one empty.

https://github.com/A3Wasteland/ArmA3_Wasteland.Altis/blob/f7171c03f1fb1416a22cc09b6a8f5ace0079b7e6/addons/vactions/config.sqf#L29-L30

**Comment by codexGW** [comment]
Nice catch, Thanks Agent
