### ISSUE TITLE
CH-67 Huron flares don't work

### ISSUE THREAD

**Issue by ReckerXF** [A3Armory/A3A_A3Wasteland.Altis#41]
Hello,

I just want to let you know that the flares on the CH-67 Huron do not work. If a Titan AA locks onto the huron and fires a missile, even if you pop a gazillion flares, the AA missile has a guaranteed hit every time. Never once have I popped flares in the huron and the missile misses.

Thanks,
Blizzard

**Comment by codexGW** [comment]
The CH-67 Huron have the same flares as the other vehicles. If a aircraft is coming straight at you a AA Titan will not miss no matter the flares

**Comment by codexGW** [comment]
Could be a game bug too
