### ISSUE TITLE
Cut grass

### ISSUE THREAD

**Issue by Merciful78** [A3Armory/A3A_A3Wasteland.Altis#43]
Per your request I am posting this reminder to add the "Cut grass" script when it is convenient.

**Comment by codexGW** [comment]
Can you send me the link or pbo for this? Can't find it after a quick google search.

**Comment by AgentRev** [comment]
It's an object, not a script. The guys from Gameaholic said it causes a lot of lag; probably not a good idea.

**Comment by codexGW** [comment]
Yeah, that would not be good.
