### ISSUE TITLE
Acquire Ownership of locked Vehicles

### ISSUE THREAD

**Issue by Merciful78** [A3Armory/A3A_A3Wasteland.Altis#45]
It is possible to "acquire ownership" of a locked vehicle. Which then allows you can "unlock" it.

**Comment by codexGW** [comment]
I couldn't reproduce this. Was this a mission vehicle, store bought, or a town spawn?

**Comment by codexGW** [comment]
He thinks it was a mission spawn. 

It could have been not saved by anybody and someone disconnected while still in the vehicle that they locked. That's not supposed to happen but maybe the disconnect event handler bugged. I'll add a check to the action just in case.

**Comment by codexGW** [comment]
This was a bug or it has been fixed
