### ISSUE TITLE
Money Money

### ISSUE THREAD

**Issue by ghost** [A3Armory/A3A_A3Wasteland.Altis#46]
You do realise by setting this variable here https://github.com/A3Armory/A3A_A3Wasteland.Altis/blob/dev/server/missions/moneyMissions/mission_TownInvasion.sqf#L41

players can access the cash before the mission ends !?...

**Comment by codexGW** [comment]
https://github.com/A3Armory/A3A_A3Wasteland.Altis/blob/dev/server/functions/fn_refillbox.sqf#L23

No this prevents that.

I see you are going over our mission file for ideas...? Wish I could do that same. Modifying A3W and hiding it in a server mod is completely against the GNU Affero General Public License. Just saying :)

**Comment by ghost** [comment]
Ideas certainly not lol,  it's all a bit vanilla for me. Just saying...

And in future please don't contact me for help or advice again. 

Good day.

**Comment by codexGW** [comment]
Ideas certainly not, but implementation and distribution of someone else code are big no no's. Just read it man. Plus its a big fuck you to Agent and the rest of the A3W community's work. It's bad enough a big community like yours doesn't have a Git and you make everything look like it was your work by not using A3Wasteland and branding everything. Community's like this in my opinion have killed the A3W development and forum. If you are going to build something on the backs of others work at least respect their wishes.

> And in future please don't contact me for help or advice again. 

Seriously? Sorry you're butt hurt. To be honest the relationship is pretty one sided. I do enjoy the chit chat though. I see why you have alienated yourself from all the A3W community's around you. Next time just maybe try to distancing yourself from them but making declarations/burning bridges is retarded and unproductive. Please stop being so sensitive.

**Comment by ghost** [comment]
blah blah blah up on your high stoned horse yet again. 

alienated? really, jesus i can't remember the last time you poked your head on the A3W forums and actually helped people.  

overviewText="A3Wasteland by Team Wasteland - edited by customcombatgaming.com";

what more do you want, a picture of you sucking revs toes?

**Comment by gravcat** [comment]
This is all super unprofessional...

Depending on the depth of these customizations, it could be argued that @ccgmatt76 is required to make this source publicly available per the license of the project and can be forced to comply or take down. However some minor things like branding are the kind of realm where I wouldn't think that's really applicable.

This is also kind of outside the scope of the issue, and shit-slinging doesn't really help anyone honestly.

**Comment by codexGW** [comment]
Looks like you're the one sucking toes. I'm talking about the license.

I help out plenty. Here's a couple of recent examples, if for some reason I
need validation from you.

http://forums.a3wasteland.com/index.php?topic=3260.msg19513#msg19513

https://github.com/A3Wasteland/ArmA3_Wasteland.Malden/commit/458858779bac534fc5054b1a9e1ae91fd4df7059

I really don't have time for much else
