### ISSUE TITLE
Explosives in Gun Store

### ISSUE THREAD

**Issue by Merciful78** [A3Armory/A3A_A3Wasteland.Altis#48]
It is possible to plant explosives inside the Gun Store once again. I successfully placed an Explosive charge at the feet of the vendor on Aug-5-2017.

**Comment by codexGW** [comment]
Was there any trick to this or was it a bug you can't reproduce?

**Comment by Merciful78** [comment]
I was able to reproduce on 8-5-17 several times doing nothing special. Checked today on 8-6-17 and was unable to perform the bug.

**Comment by codexGW** [comment]
Yeah I'm unable to reproduce this. Just Arma being Arma I guess
