### ISSUE TITLE
Zamak with the Xi'an bug

### ISSUE THREAD

**Issue by codexGW** [A3Armory/A3A_A3Wasteland.Altis#50]
I heard on Discord that the Xi'an can rearm while having a resupply truck. I will look into this later, why a vehicle can rearm while attached to another.

[DIS] Bryce da Pilot - Today at 11:01 AM
"You can definitely pick up a Zamak with the  Xi'an and occasionally it gives the option to rearm while in flight, however you wouldn't do this as rearming shuts down your engine and locks the controls, you'd die if you tried. It's not always, only once in the dozens of times I've picked up a rearm has it given the option while in flight. The condition for this was moving at 0km/h with gear down

Even at max altitude for the xian the rearming process would take so long you'd smash into the ground regardless"

**Comment by AgentRev** [comment]
Simple fix, will add a check that the truck is not attached to your vehicle in the action condition.

**Comment by codexGW** [comment]
Cool, thanks man
