### ISSUE TITLE
fn_registerKillScore.sqf errors for 13 days

### ISSUE THREAD

**Issue by codexGW** [A3Armory/A3A_A3Wasteland.Altis#51]
Any help with this would be appreciated. Brains to fried right now to see anything.

> 14:35:42 Error in expression <umedKiller && _presumedKiller != _unit) then 
> 
> if(!_friendlyFire)then{
> _bountyAm>
> 14:35:42   Error position: <then 
> 
> if(!_friendlyFire)then{
> _bountyAm>
> 14:35:42   Error then: Type if, expected Array,code
> 14:35:42 File mpmissions\__cur_mp.Malden\server\functions\fn_registerKillScore.sqf, line 76
> 14:35:42 Error in expression <umedKiller && _presumedKiller != _unit) then 
> 
> if(!_friendlyFire)then{
> _bountyAm>
> 14:35:42   Error position: <then 
> 
> if(!_friendlyFire)then{
> _bountyAm>
> 14:35:42   Error Generic error in expression

**Comment by codexGW** [comment]
https://github.com/A3Armory/A3A_A3Wasteland.Altis/blob/dev/server/functions/fn_registerKillScore.sqf#L76

**Comment by AgentRev** [comment]
delete L76: https://github.com/A3Armory/A3A_A3Wasteland.Altis/blob/e83961ba4b1b1a477517ed0134357f13dc8078ad/server/functions/fn_registerKillScore.sqf#L76
