### ISSUE TITLE
Scoreboard starting with negative kills

### ISSUE THREAD

**Issue by codexGW** [A3Armory/A3A_A3Wasteland.Altis#8]
The Scoreboard starts with negative kills on some people after a restart. Some a up to -5.
![20160715122610_1](https://cloud.githubusercontent.com/assets/9350182/16886223/c7d9e1ae-4a87-11e6-8ef0-158199da775f.jpg)

**Comment by tylers-dev** [comment]
Negative kills will happen when a player teamkills with no actual enemy kills. But that doesn't really explain why this would happen right after restart.

**Comment by codexGW** [comment]
The person with the -5 said they have -4 AT kills on the old Arma scoreboard. Is there anyway to set all that crap to 0 on join? Should I revert this as well for now? https://github.com/A3Armory/A3A_A3Wasteland.Altis/commit/8cc0c58f99628b9e20183fdae8b15ff005a8587c

**Comment by codexGW** [comment]
Not sure if this is still a issue but here's a ticket about someones kills not registering.
http://www.a3armory.com/forum/helpcenter.php?action=viewticket&tid=752
Maybe this was just a band-aid and its still happening but with 0 on the scoreboard.

**Comment by tylers-dev** [comment]
So my recent commit to this issue just kept negative numbers from showing. I was thinking it was just an anomaly that wouldn't happen often. So I'll need to find the real problem. But unless we can confirm the moment a player joins a freshly restarted server and they begin with a negative score, this is my guess to what's happening. Is it possible that persisted mines are causing inaccurate teamkills? Meaning I lay a bunch of mines as Bluefor, server restarts and I go Opfor. If a bunch of Bluefor die to those mines, is the death tracking finding the player that laid them? Even if they don't get the punishable teamkill message, it could be scoring them a teamkill. I think it has to do something with teamkills in some way, it's the only thing subtracting from player kills.

**Comment by AgentRev** [comment]
when you go back to the lobby, your mines are no longer linked to any team, the engine considers them to be neutral like scripted mines.

**Comment by tylers-dev** [comment]
Good to know. Well I'm kind of at a loss, not sure if teamkills are getting recorded some other way, or if it's not related to team kills at all. But I don't know what else would be subtracting from player kills.

**Comment by AgentRev** [comment]
add this below `params` in `fn_registerKillScore.sqf`:

```
diag_log format ["A3W_fnc_registerKillScore: %1, registered: %2, isPlayer: %3, killerDead: %4, killerGroup: %5", _this, _unit getVariable ["A3W_killScoreRegistered", false], isPlayer _unit, !alive _killer && !isPlayer _killer, group _killer];
```

this will leave clues in the server RPT

**Comment by codexGW** [comment]
https://github.com/A3Armory/A3A_A3Wasteland.Altis/commit/6b6103eacd213e145a5867066c9be3886ea3afcd
