### ISSUE TITLE
Player gear spawns

### ISSUE THREAD

**Issue by codexGW** [A3Armory/A3A_A3Wasteland.Altis#9]
Looks like this broke our system where divers and snipers are medics. @tylers-dev Can you check it out when you have the time?

Commit and merge that broke it.
https://github.com/A3Armory/A3A_A3Wasteland.Altis/commit/7c9858286bdb1a698dc49c24b73fd7660d5ff350
https://github.com/A3Armory/A3A_A3Wasteland.Altis/commit/2005d79bb967766d0d7ecf4abb80a2b8225bcabc

Original sock commits
https://github.com/A3Armory/A3A_A3Wasteland_Sock.Altis/commit/d86e0e37869f1f84ba6bcff988df387b2e3f32e5
https://github.com/A3Armory/A3A_A3Wasteland_Sock.Altis/commit/6d4322ea096a5fcfd2fd8e0acb22c4004d2158a7
https://github.com/A3Armory/A3A_A3Wasteland_Sock.Altis/commit/179b10ebfc2711e9c93bd7ca69f82145ec1142be
https://github.com/A3Armory/A3A_A3Wasteland_Sock.Altis/commit/5d7046a463cbfee8bef3dce6ab1533bce016b7a8

**Comment by AgentRev** [comment]
you should use setUnitTrait / getUnitTrait instead of changing the classnames and crap, just put it in playerSetupStart

**Comment by codexGW** [comment]
I'll revert the crap ;) and try this in the playerSetupStart.sqf. Not sure if it will work but I will test it later tonight.

```
if !(_player getUnitTrait "engineer") then
{
    _player setUnitTrait ["Medic",true];
};
```

**Comment by codexGW** [comment]
https://github.com/A3Armory/A3A_A3Wasteland.Altis/commit/ac15736976697d95086199bb07cf3ee4db3678b2
